### ISSUE TITLE
config.js cannot be read or malformed: Cannot read property 'parent' of undefined

### ISSUE THREAD

**Issue by julianxhokaxhiu** [alexindigo/configly#54]
Hi,

I've found that using the latest version of your library, this bug pops in as soon as you use a `.js` configuration. As I'm bundling all my resources through WebPack, it may be that [this line](https://github.com/alexindigo/configly/blob/master/parsers.js#L30) is not valid for that specific case, as there is no "parent of parent of parent", indeed, there is no parent at all.

Could you please sorround this call with an if so it doesn't crash for people like me who bundles your library through WebPack?

I did already a test on my side just commenting that line out and it works just fine :)

Thanks in advance!

**Proposed fix:**
```
if (jsMod.parent)
  jsMod.parent = jsMod.parent.parent.parent;
```

**Comment by alexindigo** [comment]
Hey, thanks for the interest.

Do you mind to describe the use case when you need to bundle configly with webpack? As it's strictly nodejs library? 

Thank you.

**Comment by julianxhokaxhiu** [comment]
Hi there,

it's actually a project being built within https://mercedes-benz.io and it's a command line which is using your library to fetch some configurations that will have an impact during the CLI runtime.

I'm using WebPack to bundle because it avoid installing a lot of dependencies, which by using tree-shaking and Terser, I made the whole thing to weight only 2MB ( compared to 10MB + the node_modules size ).

Your library works just fine ( I was using it since 4.1.0 ) but the latest addition in the code breaks it ( not sure if it's WebPack dependend but at least I have this scenario in my hands ).

Thank you in advance for your time!

**Comment by alexindigo** [comment]
I see. I was able to reproduce the issue with @zeit/ncc, so it’s not a webpack config quirk. :)
I’ll see how to fix it, without breaking existing functionality. Thank you for bringing it to my attention.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by julianxhokaxhiu** [comment]
I saw the patch. Looks good to me. May I ask if it's possible to publish this new package on NPM?

Thank you in advance :)

**Comment by alexindigo** [comment]
I published `configly@5.0.1`, please take a look.

**Comment by alexindigo** [comment]
I'll close the issue, feel free to continue discussion here. Thank you.

**Comment by julianxhokaxhiu** [comment]
I'll update you on Monday. Thanks :)

**Comment by julianxhokaxhiu** [comment]
Tested and works fine on my side too! Cheers :D
